name: Test

on:
  push:
    branches: [ 1.16.x ]
  pull_request:
    branches: [ 1.16.x ]

jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 8, 11 ]
        distro: [ 'zulu', 'temurin' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java-version }} ${{ matrix.distro }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distro }}
      - uses: actions/cache@v2
        name: Cache downloaded files
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Server Test
        run: ./gradlew runServerTest
      - name: Check Licenses
        run: ./gradlew checkLicenses
